# Generated by Django 5.0 on 2023-12-25 19:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('investment_id', models.AutoField(primary_key=True, serialize=False)),
                ('financial_institution', models.CharField(max_length=255)),
                ('financial_product', models.CharField(max_length=255)),
                ('rate_of_interest', models.IntegerField()),
                ('interest_payout_frequency', models.CharField(choices=[('MONTHLY', 'MONTHLY'), ('QUARTERLY', 'QUARTERLY'), ('HALF-YEARLY', 'HALF-YEARLY'), ('ANNUAL', 'ANNUAL')], max_length=255)),
                ('date_of_investment', models.DateField()),
                ('date_of_maturity', models.DateField()),
                ('crediting_bank_account', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
