# Generated by Django 5.0 on 2023-12-25 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='interest_payout_frequency',
            field=models.CharField(choices=[('MONTHLY', 'MONTHLY'), ('QUARTERLY', 'QUARTERLY'), ('HALF-YEARLY', 'HALF-YEARLY'), ('ANNUAL', 'ANNUAL')], default='ANNUAL', max_length=255),
        ),
    ]
