# Generated by Django 5.0 on 2023-12-26 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments_app', '0002_alter_investment_interest_payout_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='investment_amount',
            field=models.FloatField(default=0, max_length=15),
        ),
        migrations.AlterField(
            model_name='investment',
            name='rate_of_interest',
            field=models.FloatField(),
        ),
    ]
