# Generated by Django 5.0 on 2024-01-03 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments_app', '0003_investment_investment_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='rate_of_interest',
            field=models.FloatField(default=0, max_length=4),
        ),
    ]
